### ISSUE TITLE
On user register, add user mail to mailchimp

### ISSUE THREAD

**Issue by manelet** [bocadoapp/api#19]

**Comment by ahernandezmiro** [comment]
Tenim la casuística de login amb Instagram, on no disposem del mail del usuari (sembla que el passport-instagram no retorna el mail https://stackoverflow.com/questions/26503975/can-i-get-user-email-using-instagram-api-login). En aquest cas, simplement no s'afegeix l'usuari a mailchimp? Es pot investigar si hi ha alguna manera de vincular un usuari de IG a un de FB per poder recuperar el mail.

**Comment by manelet** [comment]
Lo dicho, que follin IG xd
